<?php
/**
 * Date 01/03/2023
 *
 * @author   Simon Siva <simonsiva13@gmail.com>
 */
return [
    'api_url' => getEnvValue('MPESA_URL', 'https://sandbox.safaricom.co.ke'),
    'max_txn' => getEnvValue('MPESA_MAX_TXN', 125000),
    'min_txn' => getEnvValue('MPESA_MIN_TXN', 100),
    'apps' => [
        'default' => [
            'consumer_key' => getEnvValue('MPESA_KEY', ''),
            'consumer_secret' => getEnvValue('MPESA_SECRET', ''),
        ],
    ],
    'cache' => [
        'driver' => getEnvValue('CACHE_DRIVER', 'file'),
        'file' => [
            'driver' => 'file',
            'path' => approot_path('cache'),
        ],
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],
    ],
    
    
    /*
    |--------------------------------------------------------------------------
    | Account API Online Config
    |--------------------------------------------------------------------------
    |
    */
    'account' => [
        'short_code' => getEnvValue('MPESA_SHORTCODE'),
        'result_url' => getEnvValue('MPESA_RESULT_URL'),
        'timeout_url' => getEnvValue('MPESA_TIMEOUT_URL'),
        'initiator_name' => getEnvValue('MPESA_INITIATOR_NAME'),
        'security_credential' => getEnvValue('MPESA_SECURITY_CREDENTIAL'),
        'security_cert' => getEnvValue('MPESA_SECURITY_CERT'),
        'identifier_type' => getEnvValue('MPESA_ACCOUNT_IDENTIFIER'),
        
        'balance' => [
            'default_command_id' => 'AccountBalance',
        ],
        'reversal' => [
            'default_command_id' => 'TransactionReversal',
        ],
        'transaction' => [
            'default_command_id' => 'TransactionStatusQuery',
        ],
        
    ],
    /*
    |--------------------------------------------------------------------------
    | LipaNaMpesa API Online Config
    |--------------------------------------------------------------------------
    |
    */
    'mpesa_online' => [
        /*
        |--------------------------------------------------------------------------
        | Paybill Number
        |--------------------------------------------------------------------------
        |
        | This is a registered Paybill Number that will be used as the Merchant ID
        | on every transaction. This is also the account to be debited.
        |
        |
        |
        */
        'short_code' => getEnvValue('MPESA_SHORTCODE'),
    
        /*
        | STK Push callback URL
        |--------------------------------------------------------------------------
        |
        | This is a fully qualified endpoint queried by Safaricom's
        | API on completion or failure of a push transaction.
        |
        */
        'callback' => getEnvValue('MPESA_CALLBACK_URL'),
    
        /*
        |--------------------------------------------------------------------------
        | SAG Passkey generated by Safaricom on registration of the Merchant's Paybill Number.
        |--------------------------------------------------------------------------
        */
        'passkey' => getEnvValue('MPESA_PASSKEY'),
    
        /*
        |--------------------------------------------------------------------------
        | Default Transaction Type set on every STK Push request
        |--------------------------------------------------------------------------
        */
        'default_transaction_type' => getEnvValue('MPESA_ONLINE_TRANSACTION_TYPE')

    ],
    /*
    |--------------------------------------------------------------------------
    | B2C API Config
    |--------------------------------------------------------------------------
    |
    */
    'b2c' => [
        'short_code' => getEnvValue('MPESA_SHORTCODE'),
        'result_url' => getEnvValue('MPESA_RESULT_URL'),
        'timeout_url' => getEnvValue('MPESA_TIMEOUT_URL'),
        'initiator_name' => getEnvValue('MPESA_INITIATOR_NAME'),
        'security_credential' => getEnvValue('MPESA_SECURITY_CREDENTIAL'),
        'security_cert' => getEnvValue('MPESA_SECURITY_CERT'),
        'identifier_type' => getEnvValue('MPESA_ACCOUNT_IDENTIFIER'),
        'default_command_id' => getEnvValue('MPESA_B2C_COMMAND'),
    ],
    /*
    |--------------------------------------------------------------------------
    | B2B API Config
    |--------------------------------------------------------------------------
    |
    */
    'b2b' => [
        'short_code' => getEnvValue('MPESA_SHORTCODE'),
        'result_url' => getEnvValue('MPESA_RESULT_URL'),
        'timeout_url' => getEnvValue('MPESA_TIMEOUT_URL'),
        'initiator_name' => getEnvValue('MPESA_INITIATOR_NAME'),
        'security_credential' => getEnvValue('MPESA_SECURITY_CREDENTIAL'),
        'security_cert' => getEnvValue('MPESA_SECURITY_CERT'),
        'identifier_type' => getEnvValue('MPESA_ACCOUNT_IDENTIFIER'),
        'default_command_id' => getEnvValue('MPESA_B2B_COMMAND'),
        'sender_identifier' => getEnvValue('MPESA_B2B_SENDER_ID'),
        'receiver_identifier' => getEnvValue('MPESA_B2B_RECEIVER_ID'),
    ],
    /*
       |--------------------------------------------------------------------------
       | C2B API Config
       |--------------------------------------------------------------------------
       |
       */
    'c2b' => [
        'short_code' => getEnvValue('MPESA_SHORTCODE'),
        'default_command_id' => getEnvValue('MPESA_C2B_COMMAND'),
        'confirmation_url' => getEnvValue('MPESA_C2B_CONFIRMATION_URL'),
        'validation_url' => getEnvValue('MPESA_C2B_VALIDATION_URL'),
        'response_type' => getEnvValue('MPESA_C2B_RESPONSE_TYPE'),
    ],
    
];
