<?php
/**
 * Date 01/03/2023
 *
 * @author   Simon Siva <simonsiva13@gmail.com>
 */
return [
    'api_url' => getenv('MPESA_URL', 'https://sandbox.safaricom.co.ke'),
    'apps' => [
        'default' => [
            'consumer_key' => getenv('MPESA_KEY', ''),
            'consumer_secret' => getenv('MPESA_SECRET', ''),
        ],
    ],
    'cache' => [
        'driver' => getenv('CACHE_DRIVER', 'file'),
        'file' => [
            'driver' => 'file',
            'path' => approot_path('cache'),
        ],
        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],
    ],
    
    
    /*
    |--------------------------------------------------------------------------
    | Account API Online Config
    |--------------------------------------------------------------------------
    |
    */
    'account' => [
        'short_code' => getenv('MPESA_SHORTCODE'),
        'result_url' => getenv('MPESA_RESULT_URL'),
        'timeout_url' => getenv('MPESA_TIMEOUT_URL'),
        'initiator_name' => getenv('MPESA_INITIATOR_NAME'),
        'security_credential' => getenv('MPESA_SECURITY_CREDENTIAL'),
        'security_cert' => getenv('MPESA_SECURITY_CERT'),
        'identifier_type' => getenv('MPESA_ACCOUNT_IDENTIFIER'),
        
        'balance' => [
            'default_command_id' => 'AccountBalance',
        ],
        'reversal' => [
            'default_command_id' => 'TransactionReversal',
        ],
        
    ],
    /*
    |--------------------------------------------------------------------------
    | LipaNaMpesa API Online Config
    |--------------------------------------------------------------------------
    |
    */
    'mpesa_online' => [
        /*
        |--------------------------------------------------------------------------
        | Paybill Number
        |--------------------------------------------------------------------------
        |
        | This is a registered Paybill Number that will be used as the Merchant ID
        | on every transaction. This is also the account to be debited.
        |
        |
        |
        */
        'short_code' => getenv('MPESA_SHORTCODE'),
    
        /*
        | STK Push callback URL
        |--------------------------------------------------------------------------
        |
        | This is a fully qualified endpoint queried by Safaricom's
        | API on completion or failure of a push transaction.
        |
        */
        'callback' => getenv('MPESA_CALLBACK_URL'),
    
        /*
        |--------------------------------------------------------------------------
        | SAG Passkey generated by Safaricom on registration of the Merchant's Paybill Number.
        |--------------------------------------------------------------------------
        */
        'passkey' => getenv('MPESA_PASSKEY'),
    
        /*
        |--------------------------------------------------------------------------
        | Default Transaction Type set on every STK Push request
        |--------------------------------------------------------------------------
        */
        'default_transaction_type' => getenv('MPESA_ONLINE_TRANSACTION_TYPE')

    ],
];
